tweet_peek/config/routes.rb
TweetPeek::Application.routes.draw do

  # devise_for :user do
  #   match '/user/sign_in/twitter' => Devise::Twitter::Rack::Signin
  #   match '/user/connect/twitter' => Devise::Twitter::Rack::Connect
  # end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  #devise_for :users

  root to: 'welcome#index', as: 'user_root'
  get '/twitter/search' => 'search#results', as: 'search_results'
  get '/twitter/top_ten' => 'search#top_ten', as: 'top_ten'
  post '/twitter/search/:twitter_handle/save' => 'user#save', as: 'save_search'
  post '/twitter/search/:twitter_handle/delete' => 'users#delete', as: 'delete_search'
  get '/twitter/favorites' => 'user#favorites', as: 'favorites'
  get '/about' => 'about#about', as: 'about'

end

tweet_peek/app/models/search.rb
class Search < ActiveRecord::Base

  has_and_belongs_to_many :users

  attr_accessible :twitter_handle
  validates :twitter_handle, presence: true


end

tweet_peek/app/models/search_controller.rb
class SearchController < ApplicationController
include Twitter
  def search
    @tweets = Twitter.user_timeline('@zreitano', {count: 200})
  end


end

tweet_peek/app/controllers/search_controller.rb
class SearchController < ApplicationController

  def results

    token = current_user.twitter_oauth_token #||= ENV['YOUR_OAUTH_TOKEN']
    secret = current_user.twitter_oauth_secret #||= ENV['YOUR_OAUTH_TOKEN_SECRET']

    client = Twitter::Client.new(
      consumer_key:  ENV['YOUR_CONSUMER_KEY'],
      consumer_secret: ENV['YOUR_CONSUMER_SECRET'],
      oauth_token: token,
      oauth_token_secret: secret
      )

    ### grab tweets ###
    tweets = client.user_timeline(params[:twitter_handle], {count: 200})

    ### Adds Search To Database ###
    search = Search.find_or_create_by_twitter_handle(params[:twitter_handle])
    search.frequency +=1
    if search.save
      # Good path
    else
      redirect_to '/', notice: "Bad search"
      # Bad path, re-render your index view. Send it an error.
    end

    list_of_tweets = []

    ### put text in array separated by space ###
      tweets.each do |tweet|
        list_of_tweets << tweet[:text] + " "
      end

    @tweet_text_hash = {}
    list_of_tweets.each do |words|
      all_words = words.split(' ')

    ### downcasing all words ###
    all_words.map! {|word| word.downcase.strip}

    ### Removing useless words ###
    useless_words =["the", "rt", "in", "of", "to", "and",
                              "a","for", "on", "is", "by", "with", "its",
                              "it's", "it", "at", "your", "you", "are",
                              "have", "has", "this", "that", "be", "from",
                              "an", "as", "their", "there", "they're", "was",
                              "then", "than", "had", "-", "—", "+", "&amp;",
                              "via", "they", "his", "her", "he", "with", "or"
                            ]

    useful_words = all_words - useless_words

    ### Iterating Through useful words
        useful_words.each do |unique_word|
          if @tweet_text_hash[unique_word]
             @tweet_text_hash[unique_word] += 1
          else
             @tweet_text_hash[unique_word] = 1
          end
        end
    end

    @tweet_text_hash = @tweet_text_hash.sort_by {|word, count|  count}
    @tweet_text_hash.reverse!

    @hashtags = @tweet_text_hash.select{|word, frequency| word.include?("#")}
    @tweet_ats = @tweet_text_hash.select{|word, frequency| word.include?("@")}
    @tweet_ats

    ### basic user info ###
    user_information = client.user(params[:twitter_handle])
    @name = user_information[:name]
    @description = user_information[:description]
    @followers = user_information[:followers_count]
    @following = user_information[:friends_count]

  end

  def top_ten
    searches = Search.all
    @popular_search_hash= {}

      #Hash of search results (key = search, value = frequency)
      searches.each do |search|
        @popular_search_hash[search.twitter_handle] = search.frequency
      end

      #Order by most frequent
      @popular_search_hash = @popular_search_hash.sort_by {|search, frequency|  frequency}
      @popular_search_hash.reverse!


  end

end

tweet_peek/app/views/search/_favorite.html.erb
 <%= button_to "Favorite", save_search_path(params[:twitter_handle]), class:"btn-large btn-primary", id:"favorite" %>

tweet_peek/app/views/search/_share.html.erb
<a href="https://twitter.com/share" class="twitter-share-button" data-url="https://tweetpeek.herokuapp.com/" data-text="Check out Tweet Peek! An analysis of the most recent 200 tweets of any user." data-size="large">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

    <p>
    </br>
    <a class="btn btn-inverse" href="https://www.facebook.com/sharer/sharer.php?u=https://tweetpeek.herokuapp.com/"
         target="_blank">Share on Facebook</a>
    </br>
    </p>

tweet_peek/app/views/search/_tables.html.erb
<table class="table" id="words">

  <thead>
    <tr>
      <th> Word </th>
      <th> Frequency </th>
    </tr>
  </thead>

  <tbody>
    <% @tweet_text_hash.each do |word, count|  %>
    <tr>
      <td id="word">  <%= truncate(word.capitalize, length: 20) %></td>
      <td>                   <%= count %></td>
    </tr>
    <% end %>
  </tbody>

  <table class="table table-striped">

    <thead>
      <tr>
        <th>Twitter Handle</th>
        <th>Frequency</th>
      </tr>
    </thead>

    <tbody>
      <% @tweet_ats.each do |tweet_ats_and_count| %>
      <% tweet_ats_and_count.each_slice(2) do |tweet_at_and_count| %>
      <tr>
        <td><%= link_to tweet_at_and_count[0].tr('^@A-Za-z0-9',''), search_results_path(twitter_handle: tweet_at_and_count[0].tr('^@A-Za-z0-9','')) %></td>
        <td><%= tweet_at_and_count[1] %></td>
      </tr>
      <% end %>
      <% end %>
    </tbody>

    <table class="table">

      <thead>
        <tr>
          <th>Hashtag</th>
          <th>Frequency</th>
        </tr>
      </thead>

      <tbody>
        <% @hashtags.each do |hashtags_and_count| %>
        <tr>
          <td id="hashtag">          <%= hashtags_and_count[0] %></td>
          <td id="hashtag_count"><%= hashtags_and_count[1] %></td>
        </tr>
        <% end %>
      </tbody>

tweet_peek/app/views/search/_top_ten.html.erb
<h1>Top Ten</h1>
<div class="container">

  <table class="table" id="top_ten">
    <thead>
      <tr>
        <th>Rank</th>
        <th>Handle</th>
        <th>Frequency</th>
      </tr>
    </thead>
    <tbody>
      <% rank = 0 %>
      <% Hash[Array(@popular_search_hash)[0...10]].each_pair do |search, frequency| %>
      <tr>
        <td class="top_ten"><%= rank += 1  %></td>
        <td class="top_ten"><%=link_to search, search_results_path(twitter_handle: search) %></td>
        <td class="top_ten"><%= frequency %></td>
      </tr>
      <% end %>
    </tbody>

  </div>
</div>

tweet_peek/app/views/search/_user_info.html.erb
<h2><%= @name.upcase %></h2>

</br>
<h4><span>Description:</span> <%= @description %>   </h4>
<h4><span>Followers:   </span> <%= @followers %>      </h4>
<h4><span>Following:   </span> <%= @following %>      </h4>
</br>

tweet_peek/app/views/search/results.html.erb
<div class="container" id="page">
  <h1>Results</h1>

  <div class="container" id="user_information">

    <%= render 'user_info' %>
    <%= render 'favorite' %>
    <%= render 'share' %>

  </div>

  <div class="container" id="results">
    <%= render partial: 'tables' %>
  </div>

</div>

tweet_peek/app/views/search/search.html.erb
<h1>Welcome</h1>

tweet_peek/app/views/search/top_ten.html.erb
<div class="container about" >
  <%= render 'top_ten' %>
</div>