tweet_peek/config/routes.rb
TweetPeek::Application.routes.draw do

  # devise_for :user do
  #   match '/user/sign_in/twitter' => Devise::Twitter::Rack::Signin
  #   match '/user/connect/twitter' => Devise::Twitter::Rack::Connect
  # end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  #devise_for :users

  root to: 'welcome#index', as: 'user_root'
  get '/twitter/search' => 'search#results', as: 'search_results'
  get '/twitter/top_ten' => 'search#top_ten', as: 'top_ten'
  post '/twitter/search/:twitter_handle/save' => 'user#save', as: 'save_search'
  post '/twitter/search/:twitter_handle/delete' => 'users#delete', as: 'delete_search'
  get '/twitter/favorites' => 'user#favorites', as: 'favorites'
  get '/about' => 'about#about', as: 'about'

end

tweet_peek/app/models/user.rb
class User < ActiveRecord::Base
  # To use devise-twitter don't forget to include the :twitter_oauth module:
  # e.g. devise :database_authenticatable, ... , :twitter_oauth

  # IMPORTANT: If you want to support sign in via twitter you MUST remove the
  #            :validatable module, otherwise the user will never be saved
  #            since it's email and password is blank.
  #            :validatable checks only email and password so it's safe to remove

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  attr_accessible  :email,
                          :password,
                          :remember_me,
                          :password_confirmation,
                          :provider,
                          :uid,
                          :name,
                          :twitter_oauth_token,
                          :twitter_oauth_secret

   devise :database_authenticatable,
              :registerable,
              :recoverable,
              :rememberable,
              :trackable,
              :token_authenticatable,
              :timeoutable,
              :omniauthable

  #has_many :authorizations, :dependent => :destroy

  has_and_belongs_to_many :searches

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
      unless user
        user = User.create(
                             name:auth.extra.raw_info.name,
                             provider:auth.provider,
                             uid:auth.uid,
                             email:auth.info.email,
                             twitter_oauth_token: auth.credentials.token,
                             twitter_oauth_secret: auth.credentials.secret,
                             password:Devise.friendly_token[0,20]
                             )
      end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.twitter_data"] && session["devise.twitter_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


end

tweet_peek/app/controllers/user_controller.rb
class UserController < ApplicationController

  def save
      s = Search.find_by_twitter_handle(params[:twitter_handle])
        unless current_user.searches.include?(s)
          current_user.searches << s
        end
      redirect_to('/twitter/favorites')
  end

  def delete
    handle = Search.find_by_twitter_handle(params[:twitter_handle])
    current_user.searches.delete(handle)
    redirect_to '/twitter/favorites'
  end

  def favorites
    if user_signed_in?
      @favorites = current_user.searches
    end
  end

end

tweet_peek/app/views/user/_favorite.html.erb
  <div class="container about" >
    <h1>Favorites</h1>
    <% @favorites.each do |favorite| %>
    <% if favorite %>
  <div class= "container about favorite" >
        <ul>
             <p> <%= link_to favorite.twitter_handle, search_results_path(twitter_handle: favorite.twitter_handle), id: "favorite"  %>
                     <%= button_to "Remove", delete_search_path(favorite.twitter_handle), class:"btn btn-danger", id:"remove_button" %></p>
      </ul>
                     <% end %>


            <% end %>

    </div>
  </div>

tweet_peek/app/views/user/_sign_in.html.erb
<div class="span6">
    <h1>Sign in:</h1>

    <p>
                             <%= form_for("user", :url => user_session_path) do |f| %></p>
    <p>Email:         <%= f.text_field :email %></p>
    <p>Password:   <%= f.password_field :password %>
    </p>
    <p>                   <%= f.check_box :remember_me %>
                              <%= f.label :remember_me %>
    </p>
    <p>                   <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter), class:"btn btn-info" %></p>
    <p>                   <%= f.submit 'Sign in', class:"btn btn-primary" %></p>
    <p>                   <%= link_to 'Sign up', new_user_registration_path %>
    <p>                   <%= link_to "Forgot your password?", new_password_path('user') %>
    </p>

                              <% end %>

</div>

tweet_peek/app/views/user/favorites.html.erb
<% if user_signed_in? %>

  <%= render partial: 'user/favorite' %>

<% else %>

  <%= render partial: 'user/sign_in' %>

<% end %>