tweet_peek/config/routes.rb
TweetPeek::Application.routes.draw do

  # devise_for :user do
  #   match '/user/sign_in/twitter' => Devise::Twitter::Rack::Signin
  #   match '/user/connect/twitter' => Devise::Twitter::Rack::Connect
  # end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  #devise_for :users

  root to: 'welcome#index', as: 'user_root'
  get '/twitter/search' => 'search#results', as: 'search_results'
  get '/twitter/top_ten' => 'search#top_ten', as: 'top_ten'
  post '/twitter/search/:twitter_handle/save' => 'user#save', as: 'save_search'
  post '/twitter/search/:twitter_handle/delete' => 'users#delete', as: 'delete_search'
  get '/twitter/favorites' => 'user#favorites', as: 'favorites'
  get '/about' => 'about#about', as: 'about'

end

tweet_peek/app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42561984-1', 'herokuapp.com');
  ga('send', 'pageview');

</script>

tweet_peek/app/views/layouts/_nav.html.erb
<div class="navbar ">
  <div class="navbar-inner">
    <ul class = "nav">
      <li><%= link_to 'Search', user_root_path %></li>
      <li><%= link_to 'Top 10', top_ten_path %></li>
      <li><%= link_to 'Favorites', favorites_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <li><%= render 'devise/menu/registration_items' %></li>
      <li><%= render 'devise/menu/login_items' %></li>
    </ul>
  </div>
</div>

tweet_peek/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
        <title>TweetPeek</title>

        <%= stylesheet_link_tag    "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>

</head>
<body>
        <%= render partial: 'layouts/analytics' %>
        <%= render partial: 'layouts/nav' %>
        <%= yield %>

</body>
</html>