tweet_peek/config/routes.rb
TweetPeek::Application.routes.draw do

  # devise_for :user do
  #   match '/user/sign_in/twitter' => Devise::Twitter::Rack::Signin
  #   match '/user/connect/twitter' => Devise::Twitter::Rack::Connect
  # end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  #devise_for :users

  root to: 'welcome#index', as: 'user_root'
  get '/twitter/search' => 'search#results', as: 'search_results'
  get '/twitter/top_ten' => 'search#top_ten', as: 'top_ten'
  post '/twitter/search/:twitter_handle/save' => 'user#save', as: 'save_search'
  post '/twitter/search/:twitter_handle/delete' => 'users#delete', as: 'delete_search'
  get '/twitter/favorites' => 'user#favorites', as: 'favorites'
  get '/about' => 'about#about', as: 'about'

end

tweet_peek/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

tweet_peek/app/views/welcome/_modal.html.erb
 <!-- Button to trigger modal -->
<a href="#myModal" role="button" class="btn-large btn-primary" id="sign_in_home" data-toggle="modal">Sign in to search</a>


<!-- Modal -->

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Sign in: With Twitter for Optimal Functionality</h3>
    </div>

  <div class="modal-body">

    <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
        <div><%= f.label :email %>
        <%= f.email_field :email, :autofocus => true %></div><br />

        <div><%= f.label :password %>
        <%= f.password_field :password %></div>

  </div>

      <div class="modal-footer">
        <%= f.submit "Sign in", class:"btn btn-primary", id:"sign_in" %>
        <button class="btn btn-action" id="close" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= link_to "Sign up", new_registration_path(resource_name), class:"btn btn-success", id:"sign_up" %>

        <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter), class:"btn btn-info", id:"sign_in_with_twitter" %>
        <% end %>
      </div>


 </div>

tweet_peek/app/views/welcome/_welcome_box_not_signed_in.erb
<div class="welcome_box">
  <h1><img src="/assets/twitter_bird.png" /><span id="title">Tweet Peek</span></h1>
  <%= render partial: "welcome/modal", :locals => { :resource => @resource,

  } %>
</div>

tweet_peek/app/views/welcome/_welcome_box_signed_in.html.erb
<div class="welcome_box">

  <h1><img src="/assets/twitter_bird.png" /><span id="title">Tweet Peek</span></h1>

  <div id="input_box">
   <%= form_tag('/twitter/search', method: 'get') do %>
   <%= text_field_tag(:twitter_handle, nil, placeholder: 'Enter a Twitter Handle') %>
   <%= submit_tag 'Search', class:"btn-large btn-primary", id:"search_button" %>
   <% end %>
 </div>

</div>

tweet_peek/app/views/welcome/index.html.erb
<a class="sash" href="https://github.com/zreitano/tweet_peek/tree/master/tweet_peek">
  <%= image_tag "fork.png", id:"sash" %></a>
<% if user_signed_in? %>

  <%= render partial: 'welcome/welcome_box_signed_in' %>

<% else %>

  <%= render partial: 'welcome/welcome_box_not_signed_in' %>

<% end %>